server:
  port: 8080
spring:
  cloud:
    nacos:
      server-addr: 192.168.240.100:8848
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi